# Automatic updated for the vulnerabilities databases, based on NVD
name: "vuln-db-update"

on:
  schedule:
    - cron: "* * * * *"

jobs:
  update-db:
    name: "Check for CVE DB updates on NVD"
    runs-on: "ubuntu-latest"

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: run updateDB script
        run: ./updateDB.py

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  notify:
    if: failure()
    name: Post Workflow Status To Slack
    needs:
      - update-db
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          # Optional Input
          icon_emoji: ':rocket:'