# Automatic updated for the vulnerabilities databases, based on NVD
name: "vuln-db-update"

on:
  schedule:
    - cron: "*/3 * * * *"

jobs:
  update-db:
    name: "Check for CVE DB updates on NVD"
    runs-on: "ubuntu-latest"

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: run updateDB script
        run: ./updateDB.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: SixSq CI Bot
          author_email: support@sixsq.com
          message: "Auto DB update from CI"
          add: "databases"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    if: failure()
    name: Post Workflow Status To Slack
    needs:
      - update-db
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          # Optional Input
          icon_emoji: ':rocket:'